services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
    depends_on:
      api:
        condition: service_healthy

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - MONGODB_URI=mongodb://mongo:27017/minishopa-kenya
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - JWT_EXPIRES_IN=7d
    ports:
      - "8080:5000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/ || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s

  mongo:
    image: mongo:7
    ports:
      - target: 27017
        published: 27017
        mode: host
